version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./dump:/dump
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}

  # app:
  #   build: .
  #   container_name: python_app
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - MONGO_URI=mongodb://mongodb:27017
  #   volumes:
  #     - .:/usr/src/app

# volumes:
#   mongo-data: